name: Dependencies

on:
  push:
  pull_request:

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Verify Dependencies
      run: |
        # Create a temporary copy of go.mod and go.sum
        cp go.mod go.mod.orig
        cp go.sum go.sum.orig

        # Run go mod tidy
        go mod tidy

        # Check if go.mod or go.sum were modified
        if ! diff -u go.mod.orig go.mod || ! diff -u go.sum.orig go.sum; then
          echo "go.mod or go.sum needs updating. Please run 'go mod tidy'"
          exit 1
        fi
