name: Lint

on:
  push:
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.x'

    - name: Format Check
      run: |
        # Check if any files need formatting
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files are not formatted correctly:"
          gofmt -l .
          echo "Please run 'gofmt -w .' to fix formatting issues"
          exit 1
        fi

    - name: Vet
      run: go vet ./...